# Generated by Django 5.0.6 on 2024-08-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryProduct',
        ),
    ]
