# Generated by Django 5.0.6 on 2024-08-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
