# Generated by Django 5.0.6 on 2024-08-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0005_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات فوتر')),
                ('address', models.TextField(verbose_name='آدرس شرکت')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل شرکت')),
                ('instagram', models.URLField(verbose_name='آدرس اینستاگرام شرکت')),
                ('telegram', models.URLField(verbose_name='آدرس تلگرام شرکت')),
                ('eitaa', models.URLField(verbose_name='آدرس ایتا شرکت')),
                ('twitter', models.URLField(verbose_name='آدرس توییتر شرکت')),
                ('phone', models.ManyToManyField(to='home_app.phonecompany', verbose_name='شماره\u200cهای تلفن شرکت')),
            ],
        ),
    ]
