# Generated by Django 5.0.6 on 2024-08-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0006_phonecompany_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='eitaa',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس ایتا شرکت'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام شرکت'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس تلگرام شرکت'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس توییتر شرکت'),
        ),
    ]
