# Generated by Django 5.0.6 on 2024-07-31 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_alter_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='product_app.productreview', verbose_name='پاسخ به'),
        ),
    ]
