# Generated by Django 5.0.6 on 2024-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_productreview_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='امتیاز'),
        ),
    ]
