# Generated by Django 5.0.6 on 2024-08-01 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_alter_address_user'),
        ('product_app', '0008_discountcode_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.address', verbose_name='آدرس'),
        ),
    ]
