# Generated by Django 5.0.6 on 2024-08-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0009_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
    ]
