# Generated by Django 5.0.6 on 2024-08-04 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0011_alter_orderitem_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('notRegistered', 'تایید نشده'), ('pending', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل شده'), ('cancelled', 'لغو شده')], default='notRegistered', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, verbose_name='درصد تخفیف'),
        ),
    ]
