# Generated by Django 5.0.6 on 2024-08-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0016_alter_product_options_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(related_name='subshops', to='product_app.category', verbose_name='دسته\u200cبندی\u200cهای فروشگاه')),
            ],
            options={
                'verbose_name': 'فروشگاه فرعی',
                'verbose_name_plural': 'فروشگاه\u200cهای فرعی',
            },
        ),
    ]
