# Generated by Django 5.0.6 on 2024-07-29 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_remove_otp_expiration_data_otp_expiration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
    ]
