# Generated by Django 5.0.6 on 2024-08-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_alter_contactus_options_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_at'], 'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس\u200c با ما'},
        ),
    ]
